### ISSUE TITLE
Default to intercept-only when no fixed effects are specified?

### ISSUE THREAD

**Issue by pitakakariki** [runehaubo/ordinal#10]
I'm trying to test the significance of a single (categorical) fixed effect, and I ran into this small problem when I speicified a null model with no fixed effects:

```
> mm1 <- clmm(SURENESS ~ PROD + (1|RESP) + (1|RESP:PROD), data = soup,
+             link = "probit", threshold = "equidistant")
> 
> mm0 <- clmm(SURENESS ~ (1|RESP) + (1|RESP:PROD), data = soup,
+             link = "probit", threshold = "equidistant")
Error in environment(fixedForm) <- environment(form) <- form.envir : 
  cannot set attribute on a symbol
> 
> mm0 <- clmm(SURENESS ~ 1 + (1|RESP) + (1|RESP:PROD), data = soup,
+             link = "probit", threshold = "equidistant")
```

Making the intercept explicit worked, but I thought I should let you know about this edge case.

Note that this also affects `drop1`:

```
> drop1(mm1, ~PROD)
Error in environment(fixedForm) <- environment(form) <- form.envir : 
  cannot set attribute on a symbol
```

**Comment by runehaubo** [comment]
Thanks for bringing this to my attention - I'll fix when I can find the time.

Cheers
Rune

**Comment by slfan2013** [comment]
Have you found time to do that?

**Comment by runehaubo** [comment]
I don't recall - check out the latest version on Github ;-) 
If it's not fixed I will likely not have time to work on it any time soon.

**Comment by runehaubo** [comment]
This is now fixed on GitHub and will be fixed on CRAN in the next couple of days.
