### ISSUE TITLE
model.matrix() method for clmm objects

### ISSUE THREAD

**Issue by MaximeHERVE** [runehaubo/ordinal#11]
Hi,
thank you very much for your package. Thanks to its ease-of-use I convinced colleagues working on ordinal variables to go from classical LMs to CLMs!
This is not really to raise an issue but rather asking for a new functionality. Would you consider implementing a model.matrix() method for clmm objects, as it already exists for clm objects?
Thanks!
Maxime

**Comment by MaximeHERVE** [comment]
Hi,
just an update to that question. Did you consider implementing a model.matrix() method for clmm objects, as it already exists for clm objects?
Thanks!
Maxime

**Comment by runehaubo** [comment]
Unfortunately I haven't found the time to consider this yet. And I probably wont find the time in the near future, but at least you are on the to-do list :~) I would be pleased to consider a pull request implementing this including appropriate tests if you are willing to put in the work.

Cheers
Rune

**Comment by MaximeHERVE** [comment]
Thanks for your answer. In fact implementation seems easy, with:
`terms.clmm <- ordinal:::terms.clm
model.matrix.clmm <- ordinal:::model.matrix.clm`
That's it!

Maxime

**Comment by runehaubo** [comment]
This is now fixed on Github and will be fixed on CRAN in the next couple of days
