### ISSUE TITLE
Function to check proportional odds ratio assumption for clmm object

### ISSUE THREAD

**Issue by yanxianl** [runehaubo/ordinal#12]
Hi,

Thank you for developing and maintaining the _ordinal_ package.

I've run clmm for my dataset but how can I check the model assumption? _Nominal_test_ works for clm object but not for clmm object. Any suggestions on how to do it in R?

**Comment by runehaubo** [comment]
Nominal effects for `clmm` models is on the to-do list (but I don't have time for it in the foreseeable future; pull-requests are welcome) but `clmm2` can handle them. If the random-effect structures allowed in `clmm2` are not enough for you then you have too look outside the ordinal package though I'm not aware of any packages that will do this.

**Comment by michaelassouline1** [comment]
Hi;

A question: The random-effect structures allowed in clmm2 is working but when when we want to run nominal_test, we get the following message: Error in UseMethod("nominal_test") : 
  no applicable method for 'nominal_test' applied to an object of class "c('clmm2', 'clm2')"
We saw that inthe tutorial the oject is clm only...
Any help?

Thanks

**Comment by kamcamonty** [comment]
Hi michaelassouline1,
I had the same problem and I found that you should [use the same model without the random effect using clm to test the assumptions](http://rcompanion.org/handbook/G_12.html).

However I still don't know what to do if assumptions are violated. If I used clm, I should use options  nominal and scale in this case, but these options are missing in clmm function...

**Comment by yanxianl** [comment]
Hi, I had the same problem. Here are the solutions I found:

You can run the model using the clmm2 function which allows nominal/scale effects in the mixed model that relax the proportional odds assumption. Then you can run a likelihood ratio test comparing the model with and without nominal/scale effect, which is equivalent to the nominal/scale_test for the clm object.

You may encounter a warning message saying "Variance-covariance matrix of the parameters is not defined" when running the mixed model using clmm2. According to[ a previous tutorial](https://www.researchgate.net/publication/265040599_A_Tutorial_on_fitting_Cumulative_Link_Models_with_the_ordinal_Package), it's an indication that "the ML estimates of some of the threshold parameters are at (plus/minus) infinity". Nevertheless, "the remaining parameters are accurately determined and the value of the log-likelihood is also accurately determined, which means that likelihood ratio tests are still available." So, if you see this warning message, you can still reliably run the likelihood ratio test to check the proportional odds assumption.

For more information, check [this paper](https://link.springer.com/article/10.1007/s11121-014-0495-x) and [this ordinal tutorial ](https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf) made by the pacakge developer.

Yanxian

**Comment by kamcamonty** [comment]
Hi yanxianl,
thank you very much for your response! I've read the paper and found it very useful. I had read the tutorial before, but it is quite difficult to understand for me.
I have tried your suggestion and I got another warning: "_1: In setStart(rho) :
  design appears to be rank-deficient, so dropping some coefs
2: clm2 may not have converged:
  optimizer ucminf terminated with max|gradient|: 0.000591027062223359_" I tried to google what does that mean, but  I wasn't successful. Did this happen to you too?
Would you tell me which function did you use for the comparison? I've tried lrtest, anova, nagelkerke and none of these worked. I found also logLik, but it doesn't compare 2 models...
And if I use the scale option, there are no assumptions any more?

**Comment by runehaubo** [comment]
Thanks @yanxianl for answering this question. I agree with what you said but I might add that there can be some uncertainty regarding the degrees of freedom in likelihood ratio tests based on fits on the boundary on the parameter space but often the likelihood ratio itself provides more than adequate information about the support of the proportional odds assumption without explicit tests. And if p-values are required reasonable boundaries on the degrees of freedom can be always be made.

Regarding the warning: `optimizer ucminf terminated with max|gradient|: 0.000591027062223359` this is (1) a warning that comes from `clm2` which is used to get starting values for the fixed effects for `clmm2` so it's not entirely important that it converges completely. (2) The convergence criterion for the `ucminf` optimizer is the maximum absolute gradient (`max|gradient|`)  of the log-likelihood function with respect to the parameters and you can see that the specified tolerance is slightly higher than the number in the warning. In this case the reported number is still very small so I would still regard this model-fit as having reached convergence - in other cases the value of the `max|gradient|` might be, say, 0.02 in which case on or more parameters might not be determined with a good precision, e.g. only one correct decimal. When the convergence criterion was not reached the function will let you know by issuing a warning and it will report the gradient so you can judge for yourself whether convergence was good enough or whether it was so bad that you need to look into the issue.

For comparison of two model fits (say two `clmm2` model fits; one with and one without a certain `nominal` structure) you can use the anova function:

    anova(model1, model2) 

will provide a likelihood ratio test (in this case of the proportional odds assumption related to the structure added to `nominal`).

Cheers
Rune

**Comment by neuroniamh** [comment]
Could somebody provide example syntax (using clmm2) on how to run these two models, with and without a relaxed proportional odds assumption?  @yanxianl  @runehaubo 

Also, I have nested random effects (family within study site), but can clmm2 only deal with one random effect?

Thank you!

**Comment by yanxianl** [comment]
Here's [the code ](https://github.com/yanxianl/AquaFly-SeawaterGutHealth-Aquaculture-2019/blob/master/analysis/code/histology.R)I used for my analysis. You can run the code online by clicking the `launch binder `badge in the project [root directory](https://github.com/yanxianl/AquaFly-SeawaterGutHealth-Aquaculture-2019).

**Comment by fsivakoff** [comment]
@yanxianl, I'm trying to run nominal_test on a clmm2 model but get the error 

Error in UseMethod("nominal_test") : 
  no applicable method for 'nominal_test' applied to an object of class "c('clmm2', 'clm2')"

It looks like you get around running the nominal_test issue by doing a likelihood ratio test between the model with "Diet" as a nominal variable and the model where "Diet" is a fixed effect. Is that correct?

**Comment by yanxianl** [comment]
Yes, that's what I did to test the proportional odds assumption.

**Comment by GeorgF92** [comment]
Hi all,

I fitted a cumulative logit mixed effects model to my data with _clmm_ function from the _ordinal_ package and would like to test the proportional odds assumption. On [this post](https://stats.stackexchange.com/questions/375628/proportional-odds-assumption-for-multilevel-data) a stats.StackExchange user suggests using a the function _multinom()_ from the _nnet_ package.

My model formulation was the following:
```
clmm_formula <- as.formula(as.factor(cover_focal_sp_prop_rescaled) ~ poly(elevation_rescaled, 2) + mowed + 
                             plot_type * elevation_rescaled * year + (1 | site_name / plotID))
eri_clmm <- clmm(clmm_formula, data = eri_removal)
summary(eri_clmm)
```

![ordinal_issue1](https://user-images.githubusercontent.com/90279836/192104471-078af9a1-8314-4454-957d-a09be7e4200c.png)

Next, I used this function on the clmm object and the output looked like this:
`nnet::multinom(eri_clmm)`
And the output looked like this:

![ordinal_issue2](https://user-images.githubusercontent.com/90279836/192104382-0897bb1e-6a89-40c7-9706-4bb8982b7bec.png)

Do you know how I should interpret this? How can I see if there is evidence for the proportional odds assumption being (or not) violated?
