### ISSUE TITLE
Random terms truncated

### ISSUE THREAD

**Issue by peterpc5j** [runehaubo/ordinal#13]
This happens whenver the random effects specification passed to clmm is longer than a certain limit - maybe 60 characters. The error generated is this one:

"Error in names(retrms) <- term.names : 
  'names' attribute [2] must be the same length as the vector [1]"

I suppose the numbers can change.

It seems to be due to this line:

    term.names <- unlist(lapply(barlist, function(x) deparse(x)))

line 220 in the current version of clmm.R.
I have made a local copy of clmm.R in which this was solved by adding a width.cutoff argument:

  term.names <- unlist(lapply(barlist, function(x) deparse(x,width.cutoff = 500)))

By the way, any plans to add a corStruct argument to clmm? Or any workaround you know of?

Thanks for the very useful package.

**Comment by runehaubo** [comment]
Thanks for the bug report and the fix! I'll plan to fix this before the next release.

A `corStruct` argument that would add a correlation structure to random-effect terms? No. That is not in current plans. If you know the correlation matrix a priori then you may be able to use the `clmmPhylo` function from the `clmm-phylo-support` branch; alternatively you may be able to modify code in that branch to fit your needs.

Cheers
Rune

**Comment by JackEdTaylor** [comment]
For the fix it might make more sense to let `deparse()` do its thing, and then rejoin the result (especially long random effects terms could even exceed the width.cutoff limit of 500).

I submitted a pull request #30 where the line is changed to:
```
term.names <- unlist(lapply(barlist, function(x) paste(deparse(x), collapse="")))
```
