### ISSUE TITLE
Confidence intervals for odds ratio of fixed effects with CLMM2

### ISSUE THREAD

**Issue by sebastien1785** [runehaubo/ordinal#25]
Hi,
I am using the package ordinal in R to run ordinal logistic regression mixed models on ordinal data with 4 categories. I have to use clmm2 because one of my explanatory variables does not satisfy the proportional odds assumption and the nominal effects are not available in clmm. However, I do not know how to extract the confidence interval for the odds ratio of the fixed effects with clmm2.

For clmm, I understand that confidence intervals of the odds ratio are obtained by transforming the limits of confidence intervals of the parameter estimates, provided by the confint method as shown below using the wine dataset:

```
require(ordinal)
fm1 <- clmm(rating ~ contact + temp + (1|judge), data = wine)
round(exp(confint(fm1)), 2)
```

However, for clmm2, the confint method only provides confidence intervals for the standard deviation of the random effects, and not for the fixed effects (here contact and temp, with the proportional odds assumption relaxed for contact in our example).

```
fm2 <- clmm2(rating ~ temp, nominal = ~ contact, random = judge, data = wine, Hess = TRUE)
pr2 <- profile(fm2)
confint(pr2)
```

Do you know any other method to obtain the confidence intervals for the fixed effects with clmm2? I have not been able to find the answer to this question anywhere.

**Comment by runehaubo** [comment]
How about:

````
> require(ordinal)
> fm1 <- clmm(rating ~ contact + temp + (1|judge), data = wine)
> confint(fm1)
                2.5 %     97.5 %
1|2        -2.9612297 -0.2861042
2|3         0.3300249  2.6967055
3|4         2.6429744  5.8140791
4|5         4.1827891  7.9947562
contactyes  0.8303439  2.8394261
tempwarm    1.8960772  4.2299162
> 
> fm2 <- clmm2(rating ~ contact + temp, random=judge, data = wine, Hess=TRUE)
> est <- coef(fm2)
> sdhat <- sqrt(diag(vcov(fm2)))
> CI <- est + tcrossprod(1.96 * sdhat, c(-1, 1))
> rownames(CI) <- names(est)
> colnames(CI) <- c("lower", "upper")
> CI <- CI[seq_len(length(est)-1), ]
> CI
                lower      upper
1|2        -2.9612507 -0.2860766
2|3         0.3299995  2.6967292
3|4         2.6429384  5.8141112
4|5         4.1827457  7.9947946
contactyes  0.8303235  2.8394432
tempwarm    1.8960493  4.2299377
> 
> fm2 <- clmm2(rating ~ temp, nominal=~contact, random=judge, data = wine, Hess=TRUE)
> est <- coef(fm2)
> sdhat <- sqrt(diag(vcov(fm2)))
> CI <- est + tcrossprod(1.96 * sdhat, c(-1, 1))
> rownames(CI) <- names(est)
> colnames(CI) <- c("lower", "upper")
> CI <- CI[seq_len(length(est)-1), ]
> CI
                     lower      upper
1|2.(Intercept) -3.0551590 -0.1856892
2|3.(Intercept)  0.2720886  2.7691986
3|4.(Intercept)  2.6288425  6.0897354
4|5.(Intercept)  3.6088345  7.9001102
1|2.contactyes  -4.2573941  0.5978651
2|3.contactyes  -3.1292257 -0.5364443
3|4.contactyes  -3.4960113 -0.5942330
4|5.contactyes  -3.2663551  0.5485697
tempwarm         1.9009599  4.2547458

```` 

You could even wrap this into a small function :-)

Cheers
Rune

**Comment by sebastien1785** [comment]
Hi Rune,

Thanks a lot, this looks great! 

Cheers,
Sebastien
