### ISSUE TITLE
Specify nominal comparisons

### ISSUE THREAD

**Issue by banamwana** [runehaubo/ordinal#26]
Thanks very much for developing and maintaining this package. I am finding it very useful for modelling enteric infections and duration of illness.

Is there a way in clm to specify comparisons for the response levels in a nominal model? Specifically, I would like to compare all levels of the response to a reference level, as 0|1, 0|2, 0|3 etc.

Reading through the vignettes, I didn't find any examples of this.

Thanks!!

**Comment by runehaubo** [comment]
Hmm, no, I don't think that falls within the scope of ordinal models. You might be in need of a multinomial model, see eg. `nnet::multinom`.

Cheers
Rune
