### ISSUE TITLE
enforcing monotonicity as constraint

### ISSUE THREAD

**Issue by kkmann** [runehaubo/ordinal#36]
Hi,

I was wondering whether the monotonicity constraint could be enforced during MLE as a constraint. Would require switichg to an external library like nlopt(r) but might get rid of the nuicance of not being able to use a fit just because the constraint is violated.

**Comment by runehaubo** [comment]
Maybe... Well, for _all_ models without nominal effects the constraint is automatically enforced, so it will only be relevant for models with nominal effects. For these models a good solution would be to implement Fisher Scoring as an estimation method, I just haven't done it (yet). But constrained MLE estimation might also be an option.
