### ISSUE TITLE
Predict for clmm model

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [runehaubo/ordinal#39]
Is there a predict method in development for the clmm model, can I use the clmm2 predict as a template for now?

Cheers

Derek

**Comment by runehaubo** [comment]
There is no predict method for clmm objects (and no development in sight)
but a fairly simple one exists for clmm2 objects.

Cheers
Rune

**Comment by derek-corcoran-barrios** [comment]
Thank you I will use that as a template
