### ISSUE TITLE
Output interpretation of the partial proportional odds model

### ISSUE THREAD

**Issue by SimoneAm** [runehaubo/ordinal#40]
Hi everybody,

I am using "clm" function (ordinal package) to explore the associations between a numeric ordinal dependent variable (5 levels, from 1 to 5) and several covariates. In particular, I am using the partial proportional odds model specifying (in "nominal =") the covariates that can vary (those variables that violated the parallel assumption) according to the DV levels. 
I find some difficulties in interpreting the output and for this I kindly ask for support. 
Variables whose coefficients of effect are constant predict the highest levels of DV. On the other hand, what do variables (those variable that can vary according to DV level) predict in the "nominal" output? 
Judging by the values ​​it seems that they predict each lower level of DV. For example, between levels 1/2 they predict level 1 (?), between 2/3 they predict 2 (?), etc.
In VGAM package manual (p. 216) is stated that "By default, the cumulative probabilities used are P (Y≤1), P (Y≤2),..., P (Y≤J).". Does the same apply to "ordinal" package? I couldn't find information on this in the manual.

Thanks in advance for your help.

Best
Simone

**Comment by runehaubo** [comment]
Please see the vignette https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf for mathematical details on the models.
