### ISSUE TITLE
Error in `model.matrix`

### ISSUE THREAD

**Issue by rvlenth** [runehaubo/ordinal#46]
The `model.matrix()` method does not work correctly for `clmm` objects:
```r
> wine.clmm <- clmm(rating ~ temp * contact + (1|judge), data = wine)
> model.matrix(wine.clmm)
Error in eval(predvars, data, env) : object 'rating' not found
```
This is important to me (i.e., the **emmeans** package) because if one happens to have a rank deficiency, we need the model matrix to extract the basis for non-estimable functions of the regression coefficients.

Closely related... In such rank-deficient cases, `coef(<clm model>)` returns `NA`s for dropped columns, whereas these are not included with `coef(<clmm model>)`. That's inconsistent and requires special handling on my part.

**Comment by rvlenth** [comment]
I should have mentioned that this seems closely related to another issue: https://github.com/runehaubo/ordinal/issues/11

**Comment by runehaubo** [comment]
A `model.matrix` method for `clmm` objects is included in the next version of ordinal.

**Comment by rvlenth** [comment]
Thanks. I have since found ways to work around all of this, but it may come in handy later on.
