### ISSUE TITLE
How to model repeated measures with clmm or clmm2?

### ISSUE THREAD

**Issue by goeckeritz** [runehaubo/ordinal#47]
Hi Rune, 

I've got a somewhat complicated dataset with repeated measures within 8 collections. I think, for the most part, I am beginning to understand how to form my model -- but I'm very confused as to how I show clmm2 that I have repeated measures. I'm thinking the correlation of repeated measures within each collection may differ from each other a bit, so I need to try an unstructured variance-covariance structure; I was thinking compound symmetry. Can clmm2 handle this? And if so, how?? I.e., what does the syntax look like?

Any help is much appreciated -- thank you so much for maintaining this package!

Kindly, 
Charity

**Comment by runehaubo** [comment]
Hi Charity,

With clmm you can only fit variance structures like those of lmer - not all
those of lme, ie. variance structures on the random effects, not those on
residuals. And usually the concern in repeated measures analyses is the
variance structure on the residuals (unstructured, compound symmetry etc).
But In ordinal regression there are no residuals so the usual thinking from
linear world does not apply here and there is no equivalent to lme. Some of
the time-to-time variation can potentially be handled by careful
specification of random-effect structures but how to do this, and the
extent to which it can be done, is not an easy task and sufficiently
unclear to me that I cannot give further concrete advice.

Cheers
Rune
