### ISSUE TITLE
ranef function overwritten by loading ordinal package

### ISSUE THREAD

**Issue by dwarton** [runehaubo/ordinal#48]
```
library(lme4)
fm1 <- lmer(Reaction ~ Days + (Days | Subject), data=sleepstudy)
ranef(fm1)
library(ordinal)
ranef(fm1)
```
The first call to `ranef` works, the second returns an error
```
Error in UseMethod("ranef") : 
  no applicable method for 'ranef' applied to an object of class "c('lmerMod', 'merMod')"
```

The reason for the error is that generic `ranef` function, rather than being imported to the `ordinal` package from `nlme`, is defined inside the package (at line 29 of [`clmm.ranef.R`](https://github.com/runehaubo/ordinal/blob/master/R/clmm.ranef.R)).  Can you please delete these lines and instead add to [`NAMESPACE`](https://github.com/runehaubo/ordinal/blob/master/NAMESPACE) `importFrom(nlme, ranef)` (which is currently actually at lines 42-43 of the file, but it has been commented out).

**Comment by runehaubo** [comment]
Thanks. Should be fixed in the next version (though fixing it was not as easy as you described it ;-)
