### ISSUE TITLE
R software crashed after I ran the model

### ISSUE THREAD

**Issue by spaudel977** [runehaubo/ordinal#50]
After I ran the following model, the software-R crashed. 
I am trying to run the model that includes one random effect, I got this issue. Variables names are perfectly coded.

m4<-clmm(Satis ~ rePS + reTL+ reMXL + (1|MJA), data=data1, link = "logit", threshold = "equidistant")

Thanks in advance

**Comment by runehaubo** [comment]
Not a reproducible problem so not something I can look into.
