### ISSUE TITLE
Warning 'length(x) = 3 > 1' in coercion to 'logical(1)' in clmm() models

### ISSUE THREAD

**Issue by verahukker** [runehaubo/ordinal#51]
Dear @runehaubo, 

Thank you for the very useful package ordinal!

I’m using the GitHub version 2020.8-22 (not CRAN version 2019.12-10 because of issue #34) in R 4.2.1 on Windows. 

My question concerns the following warning that I get when running `clmm()` models: **length(x) = 3 > 1' in coercion to 'logical(1)**. This might have to do with [this issue](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1).

The syntax of my model looks like this:

```
model = clmm(X  ~  Y1 + Y2 + Y3 + Y4 + Y1:Y2 + Y1:Y4 + (1+Y1 | subject), data = dataset, link = "logit")
``` 

I get the same warning for models with only one interaction term with Y1.

The warning only seems to appear for models with random slopes. Also, the warning disappears when I remove the `1+` part in `(1+Y1 | subject)`. When fitting a model with two by-subject slopes, the warning appears again (also when excluding the `1+` part).

Could you tell me whether I’m doing something wrong, or whether this is a bug? 

Thank you very much!

**Comment by runehaubo** [comment]
It's indeed a bug - now fixed on GitHub and will be fixed in the next version of ordinal which should be up in CRAN in the next couple of days.

Cheers
Rune
