### ISSUE TITLE
inconsistencies between HLM software and clmm results for signs for coefficients

### ISSUE THREAD

**Issue by debbiehahsvaughn** [runehaubo/ordinal#52]
I've generated a very simple multilevel ordinal model using HLM software and using the clmm function from the ordinal package in R. The threshold values and coefficients are comparable, however the signs for the coefficients (and only the coefficients; not the thresholds) are opposite (e.g., positive in HLM, negative in clmm).  This then impacts the odds ratios for the predictors.  HLM reports odds greater than one and clmm reports odds less than one.  I anticipate there is a very easy reason for what's happening, and it's just escaping me.  Can someone please advise on what I've overlooked?

**Comment by runehaubo** [comment]
There are two conventions when it comes to the sign of regression
coefficients in cumulative link models. The ordinal package uses a minus as
explained in equation (1) and section 2.4 here:
https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf

If you change the sign.location parameter to “positive” in clm.control you
get the other convention instead.

Cheers
Rune

man. 24. okt. 2022 kl. 22.54 skrev debbiehahsvaughn <
***@***.***>:
