### ISSUE TITLE
Warning message: In length(barlist) == 1 && as.character(barlist[[1]][[2]]) == "1" :

### ISSUE THREAD

**Issue by Lau505** [runehaubo/ordinal#57]
Hello,

I ran a clmm with two main factors and one random factor which is "participants". 
One of the main factors has 6 levels that can be either categorical or numerical. 
Since it is my first time running this type of model, I do not understand why I'm getting this warning. 

Do you know how could I resolve this problem?

Thank you in advance for your help and support.

**Comment by runehaubo** [comment]
This is not help desk, so if you need help and support using the software, please ask your question in an appropriate support forum such as an R help mailing list, crossValidated or similar (and let people know what you did to get the warning).
If you believe there is a bug in the package feel free to open a new issue here with proper documentation.

Cheers
Rune
