### ISSUE TITLE
Running into error with ordinal package

### ISSUE THREAD

**Issue by jessiemmeyer** [runehaubo/ordinal#66]
I am using the ordinal package to run a cumulative link mixed model on a dataset and have managed to get all of the models to work except with two environmental covariates (TUMI & LUSI). This is the error produced when trying to run these models:

> model.test.TUMI <- clmm(Score~ RepClass + Month_group + BestProp + TUMI +
+                           (1|Year) + (1|ID), data=BMdata)
Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'

It seems like others may be running into some similar issues with this package. I've looked at the structure of the data and everything seems to be formatted correctly. Additionally, this code has been adapted and when trying to run the original code on the original dataset I received the same error for the same covariates (even though the code worked when the previous project was published 2 years ago). Wondering if this is an issue with the package rather than my data? Let me know if there's anything else that would be helpful to determine the cause of this error. Thanks!

**Comment by runehaubo** [comment]
Thanks for reporting this issue. It was fixed just now, see issue #59.

/Rune
